### ISSUE TITLE
High severity Sync issue introduced through one of the dependencies 

### ISSUE THREAD

**Issue by elkinuk** [PreciselyData/PreciselyAPIsSDK-NodeJS#6]
Package `rewire` introduces Hight severity issue
![Screenshot 2022-12-09 at 16 12 44](https://user-images.githubusercontent.com/25443181/206745039-a3186289-b6d9-4ae7-b887-7e0cca1ee726.png)

based on the fact that package has not been updated for 1 year, it might be better to find a replacement for it

**Comment by murlimjha** [comment]
Fixed in latest release.
Please use the updated SDK.

For any info, please let us know.
Thanks.
