### ISSUE TITLE
Usage of deprecated package brings High severity Snyk issue

### ISSUE THREAD

**Issue by elkinuk** [PreciselyData/PreciselyAPIsSDK-NodeJS#7]
![Screenshot 2022-12-09 at 16 17 41](https://user-images.githubusercontent.com/25443181/206745898-8173f788-14df-4f27-85cf-2def0039d3e7.png)

as per npm, package `request` was deprecated https://www.npmjs.com/package/request

Please replace it

**Comment by murlimjha** [comment]
Fixed in latest release. 
Please use the updated SDK.

For any info, please let us know.
Thanks
