### ISSUE TITLE
Breaking changes introduced in 12.0.4

### ISSUE THREAD

**Issue by elkinuk** [PreciselyData/PreciselyAPIsSDK-NodeJS#8]
## Issue 1

After updating to the latest version, code that worked on 12.0.2 stopped working (code from the example in README.md)

Please see below:

![Screenshot 2022-12-22 at 18 27 54](https://user-images.githubusercontent.com/25443181/209202535-25d78577-0ba8-4d87-a2dc-2f6138eace01.png)

I didn’t have a very deep dive in the code itself, but from what I see `constructor` of API requires completely new set of the attributes now

12.0.3:
![Screenshot 2022-12-22 at 17 21 45](https://user-images.githubusercontent.com/25443181/209191939-ab2ea991-0d87-491d-8a02-128b3b97af63.png)

12.0.4:
![Screenshot 2022-12-22 at 17 24 41](https://user-images.githubusercontent.com/25443181/209201885-6ccea095-e1cc-49fc-8ac2-24325aabe110.png)

which means that we should pass attributes like:

![Screenshot 2022-12-22 at 18 25 54](https://user-images.githubusercontent.com/25443181/209202570-abbe3d21-edd1-4364-a211-cb026e637aa3.png)

PS: Is auth attribute truly optional? I had an impression that we can't use your APIs without authorisation

## Issue 2

Another breaking change that I found is that data is now coming not from `request.body` field but from `request.data` field (`request.body` comes as `undefined`)

![Screenshot 2022-12-22 at 17 49 21](https://user-images.githubusercontent.com/25443181/209197037-b733a8b7-67fd-41dd-9093-d0cddfb845e2.png)

This was changed in Readme, which is great. But changes like that are not expected in the patch update of the package, it should be a major update. In case any consumers of this package have auto update to the latest minor and patch version, their endpoints will stop working.

## Note for issue 1

I'd suggest to pass attributes as objects in every place where you require to pass 1+ attributes
It will look cleaner and be more extendable (see example of the code below)

![Screenshot 2022-12-22 at 17 32 44](https://user-images.githubusercontent.com/25443181/209192940-4de33aed-9364-459f-ba48-a5f93a570b7d.png)

if attributes were passed as object and destructured inside the constructor, this function could've looked like this:
```js
      return AddressAutocompleteServiceApi.searchV2({
        searchText,
        country: PRECISELY_COUNTRIES[country],
      })
```

Same for the baseApi constructor: if its attributes were passed as an object, new values (which are optional) would not have introduced breaking changes

<hr>
If it is possible - the best option would be to release new version 12.0.5 with changes reverted to 12.0.3 and to release all of 12.0.4 changes in 13.0.0

'
This is your decision though, I'd only ask to reflect new api in README, if possible add suggestion from the "Note for issue 1" and in the future to release changes like this in major :)

**Comment by murlimjha** [comment]
Thank you for reaching out!

The following are the updates in major release 13.0.0:

1. Released new version 12.0.5 with previous changes reverted to version 12.0.3.
2. Also released major version **13.0.0** with all changes and updated the README.
3. Regarding suggestion for **Issue 1**, SDK is generated automatically using OpenApi generator, so it is not possible to accommodate this suggestion. 

Thank You.
